name: CI
on:
  push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: node -e "console.log(process.env.HOME)"
  win:
    runs-on: windows-latest
    steps:
    - run: node -e "console.log(process.env.USERPROFILE)"
